[project]
name = "variant-to-gene"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.28.0",
    "requests>=2.31.0",
    "plotly>=5.17.0",
    "pandas>=2.0.0"
]
